### ISSUE TITLE
Remotion 2.0 Breaking changes

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#185]
What breaking changes would you like to see? We are introducing audio support in a major release and that's the chance to change stuff you don't like about Remotion.

I want to change these things:

- [x] Fix bug of sequence being 1 frame longer than it should (#28)
- [x] `--overwrite` is true by default
- [x] ~You have to pass props and composition name to `getCompositions` as well, so that you can change duration or dimensions based on props as well. (#197)~ --> we don't implement it, if you need to distinguish, can you can add more to input props
- [x] Rename user props to input props
- [x] Change the rules of when your composition gets rendered in the timeline: In addition to the main window, the composition may also get rendered to display preview images on the left side as well as in the timeline layers. Remotion may also make extra renders to gather more information for displaying the timeline. Developers code must now be more resilient to this and they cannot rely on the order of frames anymore. (#203)
- [x] Use ESBuild instead of babel-loader? #149

**Comment by JonnyBurger** [comment]
Done!
